COND_TEXT_FODDER = {
  { input="Acquire Alkahest"                                , }
, { input="Acquire Blessed Thistle"                         , }
, { input="Acquire Bugloss"                                 , }
, { input="Acquire Deni Essence Rune"                       , }
, { input="Acquire Idode Potency Rune"                      , }
, { input="Acquire Jayde Potency Rune"                      , }
, { input="Acquire Jode Potency Rune"                       , }
, { input="Acquire Kedeko Potency Rune"                     , }
, { input="Acquire Lady's Smock"                            , }
, { input="Acquire Lorkhan's Tears"                         , }
, { input="Acquire Makko Essence Rune"                      , }
, { input="Acquire Makkoma Essence Rune"                    , }
, { input="Acquire Mountain Flower"                         , }
, { input="Acquire Mudcrab Chitin"                          , }
, { input="Acquire Mudcrab Chitin: 3 / 3"                , }
, { input="Acquire Nirnroot"                                , }
, { input="Acquire Ode Potency Rune"                        , }
, { input="Acquire Oko Essence Rune"                        , }
, { input="Acquire Pristine Water"                          , }
, { input="Acquire Purified Water"                          , }
, { input="Acquire Rede Potency Rune"                       , }
, { input="Acquire Spider Egg"                              , }
, { input="Acquire Ta Aspect Rune"                          , }
, { input="Acquire Ta Aspect Rune: 1 / 1"                , }
, { input="Acquire Violet Coprinus"                         , }
, { input="Acquire Water Hyacinth"                          , }
, { input="Acquire Wormwood"                                , }
, { input="Brewers and Cooks Can Provide Recipes"           , }
, { input="Craft Aetherial Tea"                             , }
, { input="Craft Baked Apples"                              , }
, { input="Craft Baked Potato"                              , }
, { input="Craft Barley Nectar"                             , }
, { input="Craft Battaglir Chowder"                         , }
, { input="Craft Bitterlemon Tea"                           , }
, { input="Craft Bog-Iron Ale"                              , }
, { input="Craft Breton Pork Sausage"                       , }
, { input="Craft Carrot Soup"                               , }
, { input="Craft Chicken Breast"                            , }
, { input="Craft Damage Magicka Poison IX"                  , }
, { input="Craft Damage Stamina Poison IX"                  , }
, { input="Craft Drain Health Poison IX"                    , }
, { input="Craft Dram of Ravage Magicka"                    , }
, { input="Craft Dram of Stamina"                           , }
, { input="Craft Elixir of Ravage Magicka"                  , }
, { input="Craft Elixir of Stamina"                         , }
, { input="Craft Eltheric Hooch"                            , }
, { input="Craft Essence of Ravage Health"                  , }
, { input="Craft Essence of Stamina"                        , }
, { input="Craft Essence of Stamina: 0 / 1"              , }
, { input="Craft Firsthold Fruit and Cheese Plate"          , }
, { input="Craft Firsthold Fruit and Cheese Plate: 0 / 1", }
, { input="Craft Garlic Pumpkin Seeds"                      , }
, { input="Craft Ginger Wheat Beer"                         , }
, { input="Craft Golden Lager"                              , }
, { input="Craft Grand Glyph of Magicka With Ta"            , }
, { input="Craft Grand Glyph of Stamina With Ta"            , }
, { input="Craft Grandpa's Bedtime Tonic"                   , }
, { input="Craft Greater Glyph of Health With Ta"           , }
, { input="Craft Greater Glyph of Magicka With Ta"          , }
, { input="Craft Hagraven's Tonic"                          , }
, { input="Craft Jerall View Inn Carrot Cake"               , }
, { input="Craft Lemon Flower Mazte"                        , }
, { input="Craft Lilmoth Garlic Hagfish"                    , }
, { input="Craft Mammoth Snout Pie"                         , }
, { input="Craft Maormer Tea"                               , }
, { input="Craft Mazte"                                     , }
, { input="Craft Millet-Stuffed Pork Loin"                  , }
, { input="Craft Minor Glyph of Health With Ta"             , }
, { input="Craft Minor Glyph of Stamina With Ta"            , }
, { input="Craft Moderate Glyph of Magicka With Ta"         , }
, { input="Craft Monumental Glyph of Health With Ta"        , }
, { input="Craft Monumental Glyph of Stamina With Ta"       , }
, { input="Craft Muthsera's Remorse"                        , }
, { input="Craft Muthsera's Remorse: 0 / 1"              , }
, { input="Craft Nibenese Garlic Carrots"                   , }
, { input="Craft Normal Ancestor Silk Breeches"             , }
, { input="Craft Normal Ancestor Silk Epaulets"             , }
, { input="Craft Normal Ancestor Silk Robe"                 , }
, { input="Craft Normal Ash Bow"                            , }
, { input="Craft Normal Ash Restoration Staff"              , }
, { input="Craft Normal Ash Shield"                         , }
, { input="Craft Normal Beech Bow"                          , }
, { input="Craft Normal Beech Ice Staff"                    , }
, { input="Craft Normal Beech Inferno Staff"                , }
, { input="Craft Normal Beech Lightning Staff"              , }
, { input="Craft Normal Beech Shield"                       , }
, { input="Craft Normal Birch Ice Staff"                    , }
, { input="Craft Normal Birch Inferno Staff"                , }
, { input="Craft Normal Birch Lightning Staff"              , }
, { input="Craft Normal Birch Restoration Staff"            , }
, { input="Craft Normal Birch Shield"                       , }
, { input="Craft Normal Calcinium Cuirass"                  , }
, { input="Craft Normal Calcinium Gauntlets"                , }
, { input="Craft Normal Calcinium Greatsword"               , }
, { input="Craft Normal Calcinium Greaves"                  , }
, { input="Craft Normal Calcinium Sabatons"                 , }
, { input="Craft Normal Calcinium Sword"                    , }
, { input="Craft Normal Cotton Hat"                         , }
, { input="Craft Normal Cotton Sash"                        , }
, { input="Craft Normal Cotton Shoes"                       , }
, { input="Craft Normal Dwarven Cuirass"                    , }
, { input="Craft Normal Dwarven Greaves"                    , }
, { input="Craft Normal Dwarven Sword"                      , }
, { input="Craft Normal Ebonthread Breeches"                , }
, { input="Craft Normal Ebonthread Epaulets"                , }
, { input="Craft Normal Ebonthread Robe"                    , }
, { input="Craft Normal Ebony Cuirass"                      , }
, { input="Craft Normal Ebony Dagger"                       , }
, { input="Craft Normal Ebony Greaves"                      , }
, { input="Craft Normal Ebony Helm"                         , }
, { input="Craft Normal Ebony Pauldron"                     , }
, { input="Craft Normal Ebony Sword"                        , }
, { input="Craft Normal Fell Arm Cops"                      , }
, { input="Craft Normal Fell Bracers"                       , }
, { input="Craft Normal Fell Helmet"                        , }
, { input="Craft Normal Galatite Cuirass"                   , }
, { input="Craft Normal Galatite Dagger"                    , }
, { input="Craft Normal Galatite Greaves"                   , }
, { input="Craft Normal Galatite Helm"                      , }
, { input="Craft Normal Galatite Pauldron"                  , }
, { input="Craft Normal Galatite Sword"                     , }
, { input="Craft Normal Hickory Restoration Staff"          , }
, { input="Craft Normal Hickory Shield"                     , }
, { input="Craft Normal Hide Arm Cops"                      , }
, { input="Craft Normal Hide Bracers"                       , }
, { input="Craft Normal Hide Helmet"                        , }
, { input="Craft Normal Homespun Hat"                       , }
, { input="Craft Normal Homespun Sash"                      , }
, { input="Craft Normal Homespun Shoes"                     , }
, { input="Craft Normal Iron Dagger"                        , }
, { input="Craft Normal Iron Gauntlets"                     , }
, { input="Craft Normal Iron Greatsword"                    , }
, { input="Craft Normal Iron Helm"                          , }
, { input="Craft Normal Iron Pauldron"                      , }
, { input="Craft Normal Iron Sabatons"                      , }
, { input="Craft Normal Ironhide Arm Cops"                  , }
, { input="Craft Normal Ironhide Bracers"                   , }
, { input="Craft Normal Ironhide Helmet"                    , }
, { input="Craft Normal Ironthread Breeches"                , }
, { input="Craft Normal Ironthread Epaulets"                , }
, { input="Craft Normal Ironthread Robe"                    , }
, { input="Craft Normal Kresh Breeches"                     , }
, { input="Craft Normal Kresh Epaulets"                     , }
, { input="Craft Normal Kresh Hat"                          , }
, { input="Craft Normal Kresh Robe"                         , }
, { input="Craft Normal Kresh Sash"                         , }
, { input="Craft Normal Kresh Shoes"                        , }
, { input="Craft Normal Leather Arm Cops"                   , }
, { input="Craft Normal Leather Bracers"                    , }
, { input="Craft Normal Leather Helmet"                     , }
, { input="Craft Normal Linen Hat"                          , }
, { input="Craft Normal Linen Sash"                         , }
, { input="Craft Normal Linen Shoes"                        , }
, { input="Craft Normal Mahogany Ice Staff"                 , }
, { input="Craft Normal Mahogany Inferno Staff"             , }
, { input="Craft Normal Mahogany Lightning Staff"           , }
, { input="Craft Normal Mahogany Restoration Staff"         , }
, { input="Craft Normal Mahogany Shield"                    , }
, { input="Craft Normal Maple Bow"                          , }
, { input="Craft Normal Maple Ice Staff"                    , }
, { input="Craft Normal Maple Inferno Staff"                , }
, { input="Craft Normal Maple Lightning Staff"              , }
, { input="Craft Normal Maple Shield"                       , }
, { input="Craft Normal Nightwood Bow"                      , }
, { input="Craft Normal Nightwood Ice Staff"                , }
, { input="Craft Normal Nightwood Inferno Staff"            , }
, { input="Craft Normal Nightwood Lightning Staff"          , }
, { input="Craft Normal Nightwood Shield"                   , }
, { input="Craft Normal Oak Bow"                            , }
, { input="Craft Normal Oak Ice Staff"                      , }
, { input="Craft Normal Oak Inferno Staff"                  , }
, { input="Craft Normal Oak Lightning Staff"                , }
, { input="Craft Normal Oak Shield"                         , }
, { input="Craft Normal Orichalcum Dagger"                  , }
, { input="Craft Normal Orichalcum Gauntlets"               , }
, { input="Craft Normal Orichalcum Greatsword"              , }
, { input="Craft Normal Orichalcum Helm"                    , }
, { input="Craft Normal Orichalcum Pauldron"                , }
, { input="Craft Normal Orichalcum Sabatons"                , }
, { input="Craft Normal Quicksilver Cuirass"                , }
, { input="Craft Normal Quicksilver Gauntlets"              , }
, { input="Craft Normal Quicksilver Greatsword"             , }
, { input="Craft Normal Quicksilver Greaves"                , }
, { input="Craft Normal Quicksilver Sabatons"               , }
, { input="Craft Normal Quicksilver Sword"                  , }
, { input="Craft Normal Rawhide Arm Cops"                   , }
, { input="Craft Normal Rawhide Bracers"                    , }
, { input="Craft Normal Rawhide Helmet"                     , }
, { input="Craft Normal Rubedite Cuirass"                   , }
, { input="Craft Normal Rubedite Dagger"                    , }
, { input="Craft Normal Rubedite Dagger: 0 / 1"          , }
, { input="Craft Normal Rubedite Greaves"                   , }
, { input="Craft Normal Rubedite Helm"                      , }
, { input="Craft Normal Rubedite Helm: 0 / 1"            , }
, { input="Craft Normal Rubedite Pauldron"                  , }
, { input="Craft Normal Rubedite Pauldron: 0 / 1"        , }
, { input="Craft Normal Rubedite Sword"                     , }
, { input="Craft Normal Rubedo Leather Arm Cops"            , }
, { input="Craft Normal Rubedo Leather Arm Cops: 0 / 1"  , }
, { input="Craft Normal Rubedo Leather Bracers"             , }
, { input="Craft Normal Rubedo Leather Bracers: 0 / 1"   , }
, { input="Craft Normal Rubedo Leather Helmet"              , }
, { input="Craft Normal Rubedo Leather Helmet: 0 / 1"    , }
, { input="Craft Normal Ruby Ash Bow"                       , }
, { input="Craft Normal Ruby Ash Bow: 0 / 2"             , }
, { input="Craft Normal Ruby Ash Restoration Staff"         , }
, { input="Craft Normal Ruby Ash Shield"                    , }
, { input="Craft Normal Ruby Ash Shield: 0 / 1"          , }
, { input="Craft Normal Shadowhide Arm Cops"                , }
, { input="Craft Normal Shadowhide Bracers"                 , }
, { input="Craft Normal Shadowhide Helmet"                  , }
, { input="Craft Normal Shadowspun Hat"                     , }
, { input="Craft Normal Shadowspun Sash"                    , }
, { input="Craft Normal Shadowspun Shoes"                   , }
, { input="Craft Normal Silverweave Breeches"               , }
, { input="Craft Normal Silverweave Epaulets"               , }
, { input="Craft Normal Silverweave Hat"                    , }
, { input="Craft Normal Silverweave Robe"                   , }
, { input="Craft Normal Silverweave Sash"                   , }
, { input="Craft Normal Silverweave Shoes"                  , }
, { input="Craft Normal Spidersilk Breeches"                , }
, { input="Craft Normal Spidersilk Epaulets"                , }
, { input="Craft Normal Spidersilk Robe"                    , }
, { input="Craft Normal Steel Dagger"                       , }
, { input="Craft Normal Steel Gauntlets"                    , }
, { input="Craft Normal Steel Greatsword"                   , }
, { input="Craft Normal Steel Helm"                         , }
, { input="Craft Normal Steel Pauldron"                     , }
, { input="Craft Normal Steel Sabatons"                     , }
, { input="Craft Normal Voidsteel Dagger"                   , }
, { input="Craft Normal Voidsteel Gauntlets"                , }
, { input="Craft Normal Voidsteel Greatsword"               , }
, { input="Craft Normal Voidsteel Helm"                     , }
, { input="Craft Normal Voidsteel Pauldron"                 , }
, { input="Craft Normal Voidsteel Sabatons"                 , }
, { input="Craft Normal Yew Bow"                            , }
, { input="Craft Normal Yew Restoration Staff"              , }
, { input="Craft Normal Yew Shield"                         , }
, { input="Craft Nut Brown Ale"                             , }
, { input="Craft Orcrest Garlic Apple Jelly"                , }
, { input="Craft Panacea of Health"                         , }
, { input="Craft Panacea of Magicka"                        , }
, { input="Craft Pellitine Tomato Rice"                     , }
, { input="Craft Petty Glyph of Health With Ta"             , }
, { input="Craft Petty Glyph of Stamina With Ta"            , }
, { input="Craft Potion of Health"                          , }
, { input="Craft Potion of Magicka"                         , }
, { input="Craft Red Rye Beer"                              , }
, { input="Craft Redoran Peppered Melon"                    , }
, { input="Craft Roast Corn"                                , }
, { input="Craft Seaflower Tea"                             , }
, { input="Craft Sip of Health"                             , }
, { input="Craft Sip of Magicka"                            , }
, { input="Craft Solution of Stamina"                       , }
, { input="Craft Sour Mash"                                 , }
, { input="Craft Splendid Glyph of Health With Ta"          , }
, { input="Craft Splendid Glyph of Magicka With Ta"         , }
, { input="Craft Stormhold Baked Bananas"                   , }
, { input="Craft Strong Glyph of Magicka With Ta"           , }
, { input="Craft Strong Glyph of Stamina With Ta"           , }
, { input="Craft Superb Glyph of Magicka With Ta"           , }
, { input="Craft Superb Glyph of Stamina With Ta"           , }
, { input="Craft Superb Glyph of Stamina With Ta: 0 / 1" , }
, { input="Craft Three Electrum Rings"                      , }
, { input="Craft Three Platinum Rings"                      , }
, { input="Craft Treacleberry Tea"                          , }
, { input="Craft Trifling Glyph of Health With Ta"          , }
, { input="Craft Trifling Glyph of Stamina With Ta"         , }
, { input="Craft Two Copper Necklaces"                      , }
, { input="Craft Two Pewter Necklaces"                      , }
, { input="Craft Two Platinum Necklaces"                    , }
, { input="Craft Two Silver Necklaces"                      , }
, { input="Craft Two-Zephyr Tea"                            , }
, { input="Craft a Copper Necklace"                         , }
, { input="Craft a Copper Ring"                             , }
, { input="Craft a Pewter Necklace"                         , }
, { input="Craft a Pewter Ring"                             , }
, { input="Craft a Platinum Necklace"                       , }
, { input="Craft a Platinum Necklace: 0 / 1"             , }
, { input="Craft a Platinum Ring"                           , }
, { input="Craft a Platinum Ring: 0 / 1"                 , }
, { input="Craft a Silver Necklace"                         , }
, { input="Craft a Silver Ring"                             , }
, { input="Deliver Goods to Nearest Writ Quartermaster"     , }
}
